### ISSUE TITLE
MS80SH relative humidity is not logged

### ISSUE THREAD

**Issue by AdamRJensen** [AdamRJensen/SARC#76]
The last time the relative humidity of the MS80SH was logged, was May 15th.

df['MS80SH_S24053407_rh_per'].dropna()

![Image](https://github.com/user-attachments/assets/c87b78b4-3414-4864-8a64-b2bf818d56b1)

**Comment by AdamRJensen** [comment]
This is still an issue as of 01-06-2025.

**Comment by IoannisSifnaios** [comment]
There was a (stupid) mistake in the tables. The parameter is read fine from the instrument, but accidentally, the heater alert was logged in its place (you can see that when the heater started, the RH stopped).

@AdamRJensen can you send the script to the secondary at night, so that we don't lose the data? It should work now.

**Comment by AdamRJensen** [comment]
I still don't see the relative humidity being logged...

![Image](https://github.com/user-attachments/assets/87836bbe-62a6-4b7d-a13e-905725534610)

**Comment by AdamRJensen** [comment]
It is listed in the secondary fast table, so maybe we just need to wait another day... it could be that I didn't send the script right (there's no gaps in the secondary data, so that is a good indication that the script hasn't been updated)... but then why would it show from the table below

![Image](https://github.com/user-attachments/assets/12fe278c-b7ee-4bcd-8187-8e30c25481b7)

**Comment by IoannisSifnaios** [comment]
The parameter is logged properly in the file `2025-06-06_00-00-00_secondary_fast_table.csv`.

Maybe check your script (I opened it in Excel just to make sure that I don't use the same code)?

**Comment by AdamRJensen** [comment]
It is indeed there. I think I might have been looking for the MS80SHplus relative humidity which is nan these days, as the instrument does not work.
